### ISSUE TITLE
Database Hatası

### ISSUE THREAD

**Issue by hanzale** [b3rkaydem1r/gozetmen-atama-otomasyonu#1]
Tablo olusturma dosyalarının tamamının içerisinde "ankaraUni.db" veri tabanı çağrılıyor ancak tablo boş, ilgili bilgiler "ankarauni.db" içerisinde yer alıyor, düzeltildiğinde normal çalışıyor.

**Comment by berkaydemir6** [comment]
Evet güncelledim. Bilgi için teşekkürler.
